# Generated by Django 3.2.3 on 2021-06-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitanda', '0002_auto_20210613_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(default='user', max_length=250, verbose_name='nome do supermercado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='adress_district',
            field=models.CharField(max_length=250, null=True, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='order',
            name='adress_number',
            field=models.IntegerField(null=True, verbose_name='numero'),
        ),
        migrations.AlterField(
            model_name='order',
            name='adress_street',
            field=models.CharField(max_length=250, null=True, verbose_name='rua'),
        ),
        migrations.AlterField(
            model_name='order',
            name='finalized_at',
            field=models.DateTimeField(null=True, verbose_name='finalizado em '),
        ),
    ]
