# Generated by Django 3.2.3 on 2021-05-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitanda', '0003_auto_20210527_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='localization',
        ),
        migrations.AddField(
            model_name='market',
            name='adress_district',
            field=models.CharField(max_length=250, null=True, verbose_name='endereço bairo'),
        ),
        migrations.AddField(
            model_name='market',
            name='adress_number',
            field=models.IntegerField(null=True, verbose_name='endereço numero'),
        ),
        migrations.AddField(
            model_name='market',
            name='adress_street',
            field=models.CharField(max_length=250, null=True, verbose_name='endereço rua'),
        ),
        migrations.AddField(
            model_name='market',
            name='city',
            field=models.CharField(max_length=250, null=True, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='market',
            name='state',
            field=models.CharField(max_length=250, null=True, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='nome do supermercado'),
        ),
    ]
