# Generated by Django 3.2.3 on 2021-05-27 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitanda', '0004_auto_20210527_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adress_to_delivery',
        ),
        migrations.AddField(
            model_name='order',
            name='adress_district',
            field=models.CharField(max_length=250, null=True, verbose_name='endereço de entrega bairo'),
        ),
        migrations.AddField(
            model_name='order',
            name='adress_number',
            field=models.IntegerField(null=True, verbose_name='endereço de entrega numero'),
        ),
        migrations.AddField(
            model_name='order',
            name='adress_street',
            field=models.CharField(max_length=250, null=True, verbose_name='endereço de entrega rua'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=250, null=True, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=250, null=True, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cliente'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
