# Generated by Django 3.2.4 on 2021-08-10 11:23

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import kitanda.kitanda.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kitanda_tax', models.FloatField(null=True, verbose_name='taxa do kitanda')),
                ('delivery_fee_percent', models.FloatField(null=True, verbose_name='percentual da taxa de entrega')),
                ('pix_cost_percent', models.FloatField(null=True, verbose_name='porcentagem de custo com o pix')),
            ],
            options={
                'verbose_name': 'configuração',
                'verbose_name_plural': 'configuração',
                'db_table': 'base_configuration',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='nome do supermercado')),
                ('cnpj', models.CharField(max_length=14, null=True, verbose_name='cnpj')),
                ('bank', models.CharField(max_length=250, null=True, verbose_name='banco')),
                ('bank_account', models.CharField(max_length=250, null=True, verbose_name='conta do banco')),
                ('bank_agency', models.CharField(max_length=250, null=True, verbose_name='agência do banco')),
                ('pix', models.CharField(max_length=250, null=True, verbose_name='pix')),
                ('delivery_fee', models.FloatField(null=True, verbose_name='taxa de entrega')),
                ('min_order_value', models.FloatField(null=True, verbose_name='valor mínimo do pedido')),
                ('phone_number', models.CharField(max_length=18, verbose_name='telefone')),
                ('adress_street', models.CharField(max_length=250, null=True, verbose_name='rua')),
                ('adress_number', models.IntegerField(null=True, verbose_name='numero')),
                ('adress_district', models.CharField(max_length=250, null=True, verbose_name='bairro')),
                ('city', models.CharField(max_length=250, null=True, verbose_name='cidade')),
                ('state', models.CharField(max_length=250, null=True, verbose_name='estado')),
                ('latitude', models.CharField(max_length=250, null=True, verbose_name='latitude')),
                ('longitude', models.CharField(max_length=250, null=True, verbose_name='longitude')),
                ('is_active', models.BooleanField(default=False, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='atualizado em ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'mercado',
                'verbose_name_plural': 'mercados',
                'db_table': 'market',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='nome')),
                ('descript', models.CharField(max_length=250, verbose_name='descrição')),
                ('value', models.FloatField(verbose_name='valor')),
                ('offer_value', models.FloatField(verbose_name='valor de oferta')),
                ('quantity_in_stock', models.IntegerField(verbose_name='quantidade em estoque')),
                ('image', models.ImageField(default='default.png', upload_to=kitanda.kitanda.models.image_dir_path_products, verbose_name='imagem do produto')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='atualizado em ')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market', to='kitanda.market', verbose_name='mercado')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100, null=True, verbose_name='client_name')),
                ('client_cpf', models.CharField(max_length=100, null=True, verbose_name='cpf')),
                ('client_phone', models.CharField(max_length=100, null=True, verbose_name='phone')),
                ('address_number', models.CharField(max_length=100, null=True, verbose_name='número')),
                ('address_street', models.CharField(max_length=100, null=True, verbose_name='rua')),
                ('address_district', models.CharField(max_length=100, null=True, verbose_name='bairro')),
                ('total', models.FloatField(null=True, verbose_name='total')),
                ('kitanda_tax', models.FloatField(null=True, verbose_name='taxa do kitanda')),
                ('delivery_fee_percent', models.FloatField(null=True, verbose_name='percentual da taxa de entrega para o kitanda')),
                ('pix_cost_percent', models.FloatField(null=True, verbose_name='porcentagem de custo com o pix no pedido')),
                ('delivery_fee', models.FloatField(null=True, verbose_name='taxa de entrega')),
                ('pix_cost', models.FloatField(null=True, verbose_name='custo com o pix no pedido')),
                ('market_receivable', models.FloatField(null=True, verbose_name='recebível do mercado')),
                ('kitanda_receivable', models.FloatField(null=True, verbose_name='recebível do kitanda')),
                ('products', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(default='Pendente', max_length=50, verbose_name='status')),
                ('market_payed', models.BooleanField(default=False, null=True, verbose_name='o supermercado já foi pago por esse pedido?')),
                ('finalized_at', models.DateTimeField(null=True, verbose_name='finalizado em ')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='atualizado em ')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitanda.market', verbose_name='mercado')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'db_table': 'order',
            },
        ),
    ]
