# Generated by Django 3.2.4 on 2021-08-02 23:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kitanda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kitanda_tax', models.IntegerField(null=True, verbose_name='taxa do kitanda')),
                ('delivery_fee_percent', models.IntegerField(null=True, verbose_name='percentual da taxa de entrega')),
            ],
        ),
        migrations.AddField(
            model_name='market',
            name='delivery_fee',
            field=models.IntegerField(null=True, verbose_name='taxa de entrega'),
        ),
    ]
