# Generated by Django 3.2.4 on 2021-08-09 22:21

from django.db import migrations, models
import kitanda.kitanda.models


class Migration(migrations.Migration):

    dependencies = [
        ('kitanda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.png', upload_to=kitanda.kitanda.models.image_dir_path_products, verbose_name='imagem do produto'),
        ),
    ]
