# Generated by Django 3.2.4 on 2021-08-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitanda', '0002_auto_20210802_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='min_order_value',
            field=models.FloatField(null=True, verbose_name='valor mínimo do pedido'),
        ),
    ]
