# Generated by Django 3.2.4 on 2021-08-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitanda', '0003_market_min_order_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseconfiguration',
            name='delivery_fee_percent',
            field=models.FloatField(null=True, verbose_name='percentual da taxa de entrega'),
        ),
        migrations.AlterField(
            model_name='baseconfiguration',
            name='kitanda_tax',
            field=models.FloatField(null=True, verbose_name='taxa do kitanda'),
        ),
        migrations.AlterField(
            model_name='market',
            name='delivery_fee',
            field=models.FloatField(null=True, verbose_name='taxa de entrega'),
        ),
    ]
