# Generated by Django 3.2.4 on 2021-08-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitanda', '0004_auto_20210802_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseconfiguration',
            options={'verbose_name': 'configuração', 'verbose_name_plural': 'configuração'},
        ),
        migrations.AlterModelTable(
            name='baseconfiguration',
            table='base_configuration',
        ),
    ]
