# Generated by Django 3.2.4 on 2021-08-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitanda', '0005_auto_20210803_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='phone_number',
            field=models.CharField(default='+55 69 9 9999-9999', max_length=18, verbose_name='phone_number'),
            preserve_default=False,
        ),
    ]
