# Generated by Django 3.2.4 on 2021-08-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitanda', '0006_market_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='data',
            new_name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='address_city',
            field=models.CharField(max_length=100, null=True, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_district',
            field=models.CharField(max_length=100, null=True, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_number',
            field=models.CharField(max_length=100, null=True, verbose_name='número'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_state',
            field=models.CharField(max_length=100, null=True, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_street',
            field=models.CharField(max_length=100, null=True, verbose_name='rua'),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(null=True, verbose_name='total'),
        ),
    ]
