# Generated by Django 3.2.3 on 2021-05-20 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('products', models.CharField(max_length=250, verbose_name='')),
                ('payment_method', models.CharField(max_length=250, verbose_name='')),
                ('localization', models.CharField(max_length=250, verbose_name='endereço')),
                ('latitude', models.CharField(max_length=250, verbose_name='latitude')),
                ('longitude', models.CharField(max_length=250, verbose_name='longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='atualizado em ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('cnpj', models.CharField(max_length=14, verbose_name='cnpj')),
                ('payment_method', models.CharField(max_length=250, verbose_name='meio de pagamento')),
                ('localization', models.CharField(max_length=250, verbose_name='endereço')),
                ('latitude', models.CharField(max_length=250, verbose_name='latitude')),
                ('longitude', models.CharField(max_length=250, verbose_name='longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='atualizado em ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'mercado',
                'verbose_name_plural': 'mercados',
                'db_table': 'market',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='nome')),
                ('descript', models.CharField(max_length=250, verbose_name='descrição')),
                ('value', models.FloatField(verbose_name='valor')),
                ('offer_value', models.FloatField(verbose_name='valor de oferta')),
                ('quantity_in_stock', models.IntegerField(verbose_name='quantidade em estoque')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='atualizado em ')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitanda.market', verbose_name='mercado')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_value', models.FloatField(verbose_name='valor total do pedido')),
                ('kitanda_tax_per_cent', models.FloatField(verbose_name='taxa de compra kitanda')),
                ('adress_to_delivery', models.CharField(max_length=500, verbose_name='endereço do pedido')),
                ('pick_up_at_the_counter', models.BooleanField(default=False, verbose_name='pegar no balcão?')),
                ('finalized_at', models.DateTimeField(verbose_name='finalizado em ')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='atualizado em ')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitanda.client', verbose_name='cliente')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitanda.market', verbose_name='mercado')),
                ('products', models.ManyToManyField(to='kitanda.Product', verbose_name='produtos')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'db_table': 'order',
            },
        ),
    ]
